pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    parameters {
        string(name: 'BRANCH', description: 'Branch to build')
    }

    stages {
        stage ('Test commands') {
            steps {
                print 'Test'
            }
        }

        stage('Build') {
            steps {
                print 'Branch to build is ' + params.BRANCH
                echo 'Building'
                sh '''
                    cd example
                    chmod +x gradlew
                    ./gradlew build -x test
                '''
            }
        }
        stage('Test') {
            steps {
                echo 'Testing'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying'
            }
        }
    }
}